model:
  name: CNN
  channels: [16, 32, 64]
  kernels: [3,3,3]
  headless: False
  stride: 1
  padding: valid
  widths: []
  pooling_positions: [0,1,2]
  pooling_layer: 
    name: nn.AvgPool2d
    parameters: [2,2]
  conv_regularization_layer: null
  conv_activation_function:
    name: nn.ReLU
    parameters: []
  mlp_regularization_layer: null
  mlp_activation_function: null

training:
  loss: CrossEntropy
  early_stopping:
    metric: CrossEntropy
  glob:
    early_stopping:
      metric: CrossEntropy